name: Build & Deploy Docker Containers

on:
  workflow_dispatch:
    inputs:
      force_push:
        description: 'Force push?'
        type: boolean
        required: true
        default: false
  
#  release:
#    types: [published]



jobs:
  build-test-deploy-docker:
    runs-on: ubuntu-latest
    env:
      registry: ghcr.io  
    name: Build 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Container
        run: |
          tag=v0.6.1
          docker build -f container/Dockerfile -t ${{ env.registry }}/${GITHUB_REPOSITORY}:${tag} .
          docker images
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{secrets.RUN_HMRI_DOCKER}}
          password: ${{secrets.GITHUB_TOKEN }}
      - name: Deploy Container
        run: |
          docker push ${{ env.registry }}/${GITHUB_REPOSITORY} --all-tags